# Catálogo de programas SENA - extraído de app.py
CATALOGO = {
  "821100 - PRODUCCIÓN DE COMPONENTES MECÁNICOS CON MÁQUINAS CNC": {
    "proyectos": {
      "2441890 - FABRICAR ELEMENTOS MECÁNICOS CON TECNOLOGÍA DE CONTROL NUMERICO COMPUTARIZADO": {
        "nombre_completo": "2441890 - FABRICAR ELEMENTOS MECÁNICOS CON TECNOLOGÍA DE CONTROL NUMERICO COMPUTARIZADO",
        "fases": {
          "INDUCCIÓN": {
            "Inducción": {"competencias": [{"nombre": "Resultado de aprendizaje de la inducción","resultados": [{"ra": "Identificar la dinámica organizacional del SENA y el rol de la Formación Profesional Integral de acuerdo con su proyecto de vida y el desarrollo profesional","actividades": ["Asumir actitudes y valores en los diferentes ámbitos de formación, vida y trabajo.","Reconocer la identidad institucional y los procedimientos administrativos.","Incorporar a su proyecto de vida las oportunidades ofrecidas por el SENA."]}],"hD": 36,"hI": 12}]}
          },
          "ANÁLISIS": {
            "CARACTERIZAR LA MATERIA PRIMA, HERRAMIENTAS Y EQUIPOS EN EL AJUSTE MANUAL DE LAS PIEZAS.": {"competencias": [{"nombre": "Pulir piezas industriales de acuerdo con técnicas manuales y mecánicas","resultados": [{"ra": "01 Alistar materia prima e instrumentos de medición teniendo en cuenta normativa ocupacional, ambiental y procedimientos técnicos.","actividades": ["Fundamentar conceptos y principios de metrología con instrumentos análogos.","Seleccionar materiales de acuerdo con parámetros técnicos y normativa.","Trazar y cortar material de acuerdo con planos y normativa ambiental."]},{"ra": "02 Poner a punto herramientas y equipos de banco para el ajuste manual y mecánico.","actividades": ["Fundamentar conceptos y principios de trabajo con herramientas de banco.","Rectificar muelas de afilar teniendo en cuenta procedimientos técnicos.","Afilar brocas cumpliendo procedimientos técnicos y normas de seguridad."]},{"ra": "03 Ajustar manual y mecánicamente con herramientas y equipos de banco.","actividades": ["Fundamentar conceptos y principios de ajustes y tolerancias.","Aplicar técnicas de limado manual de acuerdo a parámetros establecidos.","Ejecutar operaciones de roscado manual con macho y terraja."]}],"hD": 36,"hI": 12}]},
            "REALIZAR EL DESPIECE CORRESPONDIENTE A LAS PIEZAS DEL PROYECTO SEGÚN EL DIEDRO APROPIADO.": {"competencias": [{"nombre": "Dibujar planos mecánicos de acuerdo con normas técnicas","resultados": [{"ra": "01 Dibujar elementos mecánicos de acuerdo con especificaciones técnicas.","actividades": ["Elaborar planos de acuerdo a las especificaciones técnicas del elemento.","Dibujar a mano alzada y con instrumentos la geometría del elemento mecánico.","Generar cortes, secciones y vistas ortogonales o isométricas."]},{"ra": "Modelar componentes mecánicos en software CAD según especificaciones técnicas.","actividades": ["Desarrollar ejercicios de modelado de sólidos por medio de las tecnologías CAD.","Generar modelos digitales de piezas y ensambles mecánicos.","Parametrizar los modelos digitales según tipo y dimensiones del elemento."]},{"ra": "Documentar los planos según normas técnicas.","actividades": ["Elaborar bitácora de los sólidos modelados por medio de las tecnologías CAD.","Elaborar planos de fabricación y montaje de acuerdo con normas técnicas.","Organizar archivos físicos y digitales de acuerdo a políticas de la empresa."]}],"hD": 36,"hI": 12}]},
            "CARACTERIZAR EL TORNO Y SUS PROCESOS, PARA EL MECANIZADO DE PIEZAS MECÁNICAS": {"competencias": [{"nombre": "Mecanizar pieza industrial de acuerdo con técnicas manuales y semiautomáticas","resultados": [{"ra": "Poner a punto materia prima, puesto de trabajo, máquina y herramientas de acuerdo al proceso de torneado convencional.","actividades": ["Fundamentar conceptos y principios de metrología con instrumentos análogos.","Seleccionar el material de acuerdo con especificaciones técnicas del plano.","Patronar las herramientas de acuerdo con el orden operacional de mecanizado."]},{"ra": "Ejecutar operaciones de torneado convencional de acuerdo con procedimientos técnicos y normativa ambiental.","actividades": ["Elaborar ruta operacional del proceso de mecanizado mediante torneado convencional.","Ajustar parámetros de mecanizado de acuerdo con el acabado superficial.","Mecanizar productos metalmecánicos con torno convencional según procedimientos."]},{"ra": "Mantener el torno convencional en condiciones óptimas de limpieza, ajuste y lubricación.","actividades": ["Aplicar técnicas de lubricación en la máquina teniendo en cuenta la ruta entregada.","Clasificar y disponer los residuos generados según procedimientos establecidos.","Reportar fallas y necesidades de mantenimiento según lineamientos de la empresa."]}],"hD": 36,"hI": 12}]},
            "CARACTERIZAR LA FRESADORA Y SUS PROCESOS, PARA EL MECANIZADO DE PIEZAS MECÁNICAS": {"competencias": [{"nombre": "Mecanizado de piezas en Tornos y Fresadoras Convencionales","resultados": [{"ra": "Alistar materia prima, puesto de trabajo, máquina y herramientas de fresado convencional.","actividades": ["Identificar los diferentes instrumentos de medición que intervienen en el proceso.","Ajustar las características dimensionales del producto según especificaciones.","Revisar la calidad del producto (acabados, tolerancias, dimensiones y geometría)."]},{"ra": "Mecanizar productos metalmecánicos con fresadora convencional cumpliendo especificaciones técnicas.","actividades": ["Realizar orden operacional de las piezas a mecanizar con parámetros de corte.","Fabricar pieza con operaciones básicas de fresado según especificaciones técnicas.","Fabricar pieza con operaciones propias de cabezal divisor según especificaciones."]},{"ra": "Mantener la fresadora convencional en condiciones óptimas de limpieza, ajuste y lubricación.","actividades": ["Aplicar técnicas de lubricación en la fresadora según ruta de mantenimiento.","Almacenar el refrigerante usado de acuerdo con normas medioambientales.","Informar fallas e inspección de la máquina según lineamientos de la empresa."]}],"hD": 48,"hI": 0}]}
          },
          "PLANEACIÓN": {
            "PREPARAR LOS INSUMOS REQUERIDOS PARA LA ELABORACIÓN DE LOS PRODUCTOS METALMECÁNICOS.": {"competencias": [{"nombre": "Alistar máquina herramienta de control numérico de acuerdo con especificaciones técnicas","resultados": [{"ra": "01 Alistar materia prima del producto según especificaciones técnicas.","actividades": ["Seleccionar materiales para la fabricación de las piezas metalmecánicas.","Utilizar técnicamente los instrumentos de medición de acuerdo a la pieza.","Cortar el material de acuerdo al plano de fabricación y procedimientos técnicos."]}],"hD": 36,"hI": 12}]},
            "PLANEAR EL PROCESO DE FABRICACIÓN, DE ACUERDO CON REQUERIMIENTOS TÉCNICOS.": {"competencias": [{"nombre": "Alistar máquina herramienta CNC de acuerdo con especificaciones técnicas","resultados": [{"ra": "02 Alistar maquinaria de Control Numérico Computarizado y herramientas de acuerdo al proceso de mecanizado.","actividades": ["Fundamentar conceptos y principios de los tratamientos térmicos y durezas.","Verificar estado de la máquina CNC de acuerdo al proceso a realizar.","Ajustar parámetros de mecanizado en la máquina herramienta CNC."]}],"hD": 36,"hI": 12}]},
            "DESARROLLAR LOS PROTOTIPOS REQUERIDOS PARA EL PROCESO DE MECANIZADO.": {"competencias": [{"nombre": "Mecanizar pieza industrial de acuerdo con sistema de control numérico","resultados": [{"ra": "Modelar prototipos teniendo en cuenta las especificaciones técnicas y requerimientos del cliente.","actividades": ["Desarrollar prototipos del proyecto de Formación en software CAD.","Generar plano técnico de las piezas según las especificaciones del producto.","Verificar en el simulador el programa del torno y fresadora según geometría."]}],"hD": 216,"hI": 72}]},
            "CREAR LAS RUTAS Y SECUENCIAS DE MECANIZADO PARA LAS MAQUINAS HERRAMIENTAS CNC.": {"competencias": [{"nombre": "Mecanizar pieza industrial de acuerdo con sistema de control numérico","resultados": [{"ra": "Generar rutas de mecanizado para Tornos de Control Numérico Computarizado.","actividades": ["Programar tornos CNC de acuerdo con procedimientos técnicos.","Establecer coordenadas en el torno de acuerdo a geometría de la pieza.","Documentar los programas del torno de acuerdo a procedimientos de mecanizado."]},{"ra": "Generar rutas de mecanizado para Fresadoras de Control Numérico Computarizado.","actividades": ["Programar fresadoras CNC de acuerdo con procedimientos técnicos.","Establecer coordenadas en la fresadora de acuerdo a geometría de la pieza.","Optimizar en el simulador el programa de la fresadora según geometría."]},{"ra": "Generar rutas de mecanizado para Centros de Mecanizado CNC.","actividades": ["Programar centros de mecanizado CNC con ayuda de software CAM.","Simular el programa de la pieza a fabricar según el control de la máquina.","Mecanizar la pieza en las máquinas CNC cumpliendo especificaciones técnicas."]}],"hD": 36,"hI": 12}]}
          },
          "EJECUCIÓN Y EVALUACIÓN": {
            "PRODUCIR EL MECANIZADO DE LAS PIEZAS EN MAQUINAS HERRAMIENTAS CNC.": {"competencias": [{"nombre": "Mecanizar pieza industrial de acuerdo con sistema de control numérico","resultados": [{"ra": "Fabricar piezas en Centros de Mecanizado de control numérico computarizado.","actividades": ["Programar centros de mecanizado CNC con ayuda de software CAM.","Establecer coordenadas en los centros de mecanizado según geometría.","Verificar que el proceso y producto final cumplan requerimientos técnicos."]},{"ra": "Fabricar piezas en Torno de control numérico computarizado.","actividades": ["Elaborar piezas requeridas en el Proyecto de Formación con torno CNC.","Ajustar parámetros del torno de acuerdo con el acabado superficial.","Revisar la calidad del producto torneado según planos entregados."]},{"ra": "Fabricar piezas en Fresadora de control numérico computarizado.","actividades": ["Manejar software CAD-CAM para generar las rutas de mecanizado en fresadora.","Fresar con diferentes técnicas teniendo en cuenta la geometría de la pieza.","Determinar parámetros de corte según especificaciones de tolerancias y acabados."]}],"hD": 180,"hI": 60}]},
            "GESTIONAR LA PRODUCCIÓN EN ATENCIÓN A LOS REQUERIMIENTOS TÉCNICOS.": {"competencias": [{"nombre": "Programar la producción según métodos y parámetros técnicos","resultados": [{"ra": "Organizar proceso productivo de acuerdo a órdenes de fabricación, tiempos, mano de obra y materiales.","actividades": ["Programar producción de acuerdo con estándares de fabricación.","Diseñar cronogramas de fabricación dependiendo del proceso de mecanizado.","Elaborar diagramas de Gantt y listas de chequeo según programa de producción."]},{"ra": "Diseñar programa de producción de piezas metalmecánicas según requerimientos y estándares.","actividades": ["Elaborar el control estadístico y de calidad de las piezas fabricadas.","Elaborar informe de producción de acuerdo con el tiempo estándar establecido.","Calcular la capacidad de trabajo de las máquinas de mecanizado."]}],"hD": 108,"hI": 36}]}
          }
        }
      },
      "3343700 - FABRICACIÓN DE COMPONENTES MECÁNICOS CON MÁQUINAS HERRAMIENTAS CNC PARA EL SECTOR INDUSTRIAL DEL ATLÁNTICO": {
        "nombre_completo": "3343700 - FABRICACIÓN DE COMPONENTES MECÁNICOS CON MÁQUINAS HERRAMIENTAS CNC PARA EL SECTOR INDUSTRIAL DEL ATLÁNTICO",
        "fases": {
          "IDENTIFICACIÓN": {
            "DETERMINAR LAS ESPECIFICACIONES TÉCNICAS DEL PROCESO DE FABRICACIÓN DE UN COMPONENTE MECÁNICO.": {"competencias": [{"nombre": "290201212 - ALISTAMIENTO DE MATERIA PRIMA CNC","resultados": [{"ra": "01. Alistar materia prima del producto según especificaciones técnicas.","actividades": ["Identificar el tipo de material a mecanizar teniendo en cuenta sus propiedades.","Seleccionar y cortar el material de acuerdo al plano de fabricación.","Cumplir normas medioambientales, de seguridad y salud ocupacional."]},{"ra": "02. Alistar maquinaria CNC y herramientas de acuerdo al proceso de mecanizado.","actividades": ["Fundamentar conceptos y principios de metrología con instrumentos análogos.","Verificar estado de la máquina de acuerdo al proceso a realizar.","Ajustar herramienta de corte teniendo en cuenta el proceso de mecanizado."]}],"hD": 36,"hI": 12}]}
          },
          "ALISTAMIENTO": {
            "DEFINIR LA SECUENCIA OPERACIONAL PARA LA FABRICACIÓN DE UN COMPONENTE MECÁNICO.": {"competencias": [{"nombre": "290201213 - MECANIZADO DE PIEZAS CNC","resultados": [{"ra": "03. Modelar prototipos teniendo en cuenta las especificaciones técnicas y requerimientos del cliente.","actividades": ["Desarrollar prototipos del proyecto de Formación en software CAD.","Generar plano técnico de las piezas según las especificaciones del producto.","Establecer coordenadas en el torno de acuerdo a geometría de la pieza."]}],"hD": 216,"hI": 72}]}
          },
          "FABRICACIÓN": {
            "PRODUCIR COMPONENTES MECÁNICOS CON MÁQUINAS HERRAMIENTAS CNC": {"competencias": [{"nombre": "290201213 - MECANIZADO DE PIEZAS UTILIZANDO MÁQUINAS CNC","resultados": [{"ra": "04. Generar rutas de mecanizado para Tornos CNC.","actividades": ["Programar tornos, fresadoras y centros de mecanizado CNC.","Establecer coordenadas en el torno de acuerdo a geometría de la pieza.","Documentar los programas del torno de acuerdo a procedimientos de mecanizado."]},{"ra": "02. Generar rutas de mecanizado para Fresadoras CNC.","actividades": ["Programar fresadoras CNC de acuerdo con procedimientos técnicos.","Optimizar en el simulador el programa de la fresadora según geometría.","Determinar parámetros de mecanizado para la fresadora CNC."]},{"ra": "06. Fabricar piezas en Centros de Mecanizado CNC.","actividades": ["Programar tornos, fresadoras y centros de mecanizado CNC con ayuda de software CAM.","Verificar que el proceso y producto final cumplan requerimientos técnicos.","Controlar las dimensiones del producto en el mecanizado CNC."]},{"ra": "01. Fabricar piezas en Torno CNC.","actividades": ["Elaborar piezas requeridas en el Proyecto de Formación con torno CNC.","Ajustar parámetros del torno de acuerdo con el acabado superficial.","Revisar la calidad del producto torneado según planos entregados."]},{"ra": "05. Fabricar piezas en Fresadora CNC.","actividades": ["Manejar software CAD-CAM para generar las rutas de mecanizado en fresadora.","Fresar con diferentes técnicas teniendo en cuenta la geometría de la pieza.","Determinar parámetros de corte según especificaciones de tolerancias y acabados."]}],"hD": 180,"hI": 60}]}
          },
          "MEJORAMIENTO": {
            "Ensamblar los componentes mecánicos fabricados aplicando estrategias de solución": {"competencias": [{"nombre": "RESULTADOS DE APRENDIZAJE ETAPA PRÁCTICA","resultados": [{"ra": "Aplicar en la resolución de problemas reales del sector productivo los conocimientos, habilidades y destrezas pertinentes a las competencias del programa de formación.","actividades": ["Aplicar estrategias y metodologías de autogestión en el sector productivo.","Resolver problemas reales integrando las competencias adquiridas durante la formación.","Presentar informe de actividades realizadas en la etapa productiva."]}],"hD": 0,"hI": 0}]}
          }
        }
      }
    }
  },
  "223310 - GESTIÓN DE LA PRODUCCIÓN INDUSTRIAL": {
    "proyectos": {
      "3068368 - LEAN MANUFACTURING COMO ESTRATEGIA EMPRESARIAL PARA LA OPTIMIZACIÓN INDUSTRIAL": {
        "nombre_completo": "3068368 - LEAN MANUFACTURING COMO ESTRATEGIA EMPRESARIAL PARA LA OPTIMIZACIÓN INDUSTRIAL DE LA MIPYMES EN EL DEPARTAMENTO DEL ATLÁNTICO",
        "fases": {
          "PLANEACIÓN": {
            "DIAGNOSTICO OPERATIVO FUNCIONAL INDUSTRIAL": {"competencias": [{"nombre": "ORGANIZAR LAS ACTIVIDADES DE PRODUCCIÓN DE ACUERDO CON LOS OBJETIVOS EMPRESARIALES.","resultados": [{"ra": "DIAGNOSTICAR EL ENTORNO LEGAL, ORGANIZACIONAL, TECNOLÓGICO, ECONÓMICO, AMBIENTAL Y COMPETITIVO DEL SISTEMA PRODUCTIVO.","actividades": ["Identificar el entorno legal, organizacional, tecnológico, económico, ambiental y competitivo del sistema productivo."]},{"ra": "ELABORAR EL DISEÑO O REDISEÑO DE DISTRIBUCIÓN EN PLANTA CONFORME A NORMAS ESTABLECIDAS.","actividades": ["Proponer el rediseño de planta como acción de mejora a partir del análisis de la distribución actual."]},{"ra": "GENERAR LA DOCUMENTACIÓN PARA LA ORGANIZACIÓN DE LAS ACTIVIDADES DE PRODUCCIÓN.","actividades": ["Elaborar la documentación del sistema productivo para su estandarización y control."]},{"ra": "ESTABLECER EL SISTEMA PRODUCTIVO DE ACUERDO CON EL NIVEL DE TRANSFORMACIÓN.","actividades": ["Determinar el sistema productivo teniendo en cuenta los diferentes niveles de transformación."]}],"hD": 44,"hI": 11}]}
          },
          "HACER": {
            "IMPLEMENTACIÓN OPERATIVO FUNCIONAL INDUSTRIAL": {"competencias": [{"nombre": "CONTROLAR EL FLUJO DE MATERIALES Y DE INFORMACIÓN SEGÚN REQUERIMIENTOS DEL PROCESO PRODUCTIVO","resultados": [{"ra": "COORDINAR EL FLUJO DE MATERIALES Y DE LA INFORMACIÓN, SEGÚN LOS PROCEDIMIENTOS DE LA ORGANIZACIÓN","actividades": ["Evaluar el flujo de materiales y la información según los procedimientos de la organización."]},{"ra": "ADMINISTRAR LOS INVENTARIOS DE MATERIALES SEGÚN PROCEDIMIENTOS DE LA ORGANIZACIÓN","actividades": ["Establecer el procedimiento para administrar y determinar las condiciones de almacenamiento."]}],"hD": 44,"hI": 11}]}
          },
          "VERIFICAR": {
            "MEJORAR Y CONTROLAR": {"competencias": [{"nombre": "CONTROLAR LA CALIDAD DE LOS PROCESOS DE ACUERDO CON LA NORMATIVIDAD VIGENTE","resultados": [{"ra": "INSPECCIONAR EL COMPORTAMIENTO DE LAS VARIABLES DEL PROCESO Y DEL PRODUCTO.","actividades": ["Verificación e Inspección del Comportamiento de Variables del Proceso y del Producto."]},{"ra": "ELABORAR LAS CARTAS DE CONTROL Y LA INTERPRETACIÓN DEL COMPORTAMIENTO ESTADÍSTICO.","actividades": ["Diseño e Interpretación de Gráficas de Control para el Monitoreo Estadístico de Procesos."]}],"hD": 132,"hI": 33}]}
          },
          "ACTUAR": {
            "MEJORA CONTINUA": {"competencias": [{"nombre": "IMPLEMENTAR HERRAMIENTAS DE OPTIMIZACIÓN DE RECURSOS PARA EL MEJORAMIENTO DE LOS PROCESOS","resultados": [{"ra": "ESTABLECER EL PLAN DE MEJORAMIENTO DE ACUERDO CON LA TÉCNICA DE OPTIMIZACIÓN.","actividades": ["Elaborar una propuesta de optimización a partir de un proceso productivo seleccionado."]},{"ra": "IMPLEMENTAR EL PLAN DE MEJORAMIENTO AL PROCESO PRODUCTIVO REAL.","actividades": ["Implementar herramientas de gestión para la optimización del proceso productivo."]}],"hD": 30,"hI": 0}]}
          }
        }
      }
    }
  },
  "221402 - ASEGURAMIENTO METROLOGICO INDUSTRIAL": {
    "proyectos": {
      "2721554 - IMPLEMENTACIÓN DE UN SISTEMA DE GESTIÓN METROLÓGICA": {
        "nombre_completo": "2721554 - IMPLEMENTACIÓN DE UN SISTEMA DE GESTIÓN METROLÓGICA PARA LOS PROCESOS DE PRODUCCIÓN Y ASEGURAMIENTO DE LA CALIDAD EN UNA INDUSTRIA DE MANUFACTURA",
        "fases": {
          "ANÁLISIS": {
            "Analizar la información de los componentes del sistema de gestión metrológica.": {"competencias": [{"nombre": "Determinación de necesidades metrológicas","resultados": [{"ra": "Caracterizar requerimientos del sistema metrológico de la organización de acuerdo con políticas y requisitos.","actividades": ["Identificar requisitos y características del sistema metrológico de la organización."]}],"hD": 72,"hI": 24}]}
          },
          "Planeación": {
            "Definir acciones para implementar el sistema de gestión de las mediciones.": {"competencias": [{"nombre": "Determinación de necesidades metrológicas","resultados": [{"ra": "Definir recursos requeridos para la ejecución de funciones metrológicas de acuerdo con necesidades del proceso.","actividades": ["Definir recursos requeridos para la ejecución de funciones metrológicas."]}],"hD": 36,"hI": 12}]}
          },
          "Ejecución": {
            "Ejecutar procedimientos de medición según las especificaciones dadas por normatividad.": {"competencias": [{"nombre": "Operación instrumentos de medida","resultados": [{"ra": "Efectuar mediciones de longitud en procesos y productos según normatividad vigente.","actividades": ["Efectuar mediciones de longitud en procesos y productos según normatividad vigente."]},{"ra": "Efectuar mediciones de masa en procesos y productos según normatividad vigente.","actividades": ["Efectuar mediciones de masa en procesos y productos según normatividad vigente."]},{"ra": "Efectuar mediciones de temperatura en procesos y productos según normatividad vigente.","actividades": ["Efectuar mediciones de temperatura en procesos y productos según normatividad vigente."]}],"hD": 36,"hI": 12}]}
          },
          "Evaluación": {
            "Evaluar el proceso de implementación del sistema de gestión de las mediciones.": {"competencias": [{"nombre": "Control de calidad de procesos de medición","resultados": [{"ra": "Evaluar el cumplimiento de las especificaciones del proceso y el producto de acuerdo con normativa vigente.","actividades": ["Evaluar el cumplimiento de las especificaciones del proceso y el producto."]},{"ra": "Auditar sistema de gestión de acuerdo con procedimientos técnicos y normativa vigente.","actividades": ["Auditar sistema de gestión de acuerdo con procedimientos técnicos y normativa vigente."]}],"hD": 108,"hI": 36}]}
          }
        }
      }
    }
  },
  "223318 - PROCESOS DE MANUFACTURA": {
    "proyectos": {
      "3473816 - OPERACIÓN DE LOS PROCESOS PARA EL CONTROL, MANTENIMIENTO Y SEGUIMIENTO DE LA PRODUCTIVIDAD": {
        "nombre_completo": "3473816 - OPERACIÓN DE LOS PROCESOS PARA EL CONTROL, MANTENIMIENTO Y SEGUIMIENTO DE LA PRODUCTIVIDAD EN LAS ORGANIZACIONES DE MANUFACTURA Y SERVICIOS DEL DEPARTAMENTO DEL ATLANTICO",
        "fases": {
          "PLANEAR": {
            "PREPARAR LOS RECURSOS PARA REALIZAR LAS ACTIVIDADES SEGÚN EL PROGRAMA DE PRODUCCIÓN": {"competencias": [{"nombre": "ORGANIZACIÓN DE LAS ACTIVIDADES DE PRODUCCIÓN.","resultados": [{"ra": "Describir entorno legal, organizacional, tecnológico, económico, ambiental y competitivo de la empresa según el sector industrial y económico al que pertenece.","actividades": ["Identificar los factores socioeconómicos, ambientales y legales que influyen en el sistema productivo de la organización."]},{"ra": "Alistar recursos teniendo en cuenta las tareas de producción y procedimientos de seguridad y salud en el trabajo","actividades": ["Relacionar los factores de riesgo que permiten identificar áreas con mayor riesgo para la salud del recurso humano."]}],"hD": 20,"hI": 5}]}
          },
          "CONTROLAR": {
            "PROPONER ACCIONES DE MEJORA NECESARIAS PARA EL FORTALECIMIENTO DE PROCESOS Y SERVICIOS": {"competencias": [{"nombre": "IMPLEMENTACIÓN DEL PLAN DE CALIDAD EN EL ÁREA DE PRODUCCIÓN.","resultados": [{"ra": "INTERPRETAR LAS CARTAS DE CONTROL Y EL COMPORTAMIENTO ESTADÍSTICO DE LOS DATOS DE LAS VARIABLES.","actividades": ["Interpretar las cartas de control de variables del proceso productivo, aplicando herramientas estadísticas."]}],"hD": 35,"hI": 9}]}
          },
          "EJECUTAR": {
            "DESARROLLAR LAS ACTIVIDADES DE LOS PROCESOS PRODUCTIVOS Y DE SERVICIOS": {"competencias": [{"nombre": "IMPLEMENTACIÓN DEL PLAN DE CALIDAD EN EL ÁREA DE PRODUCCIÓN.","resultados": [{"ra": "REALIZAR MEDICIONES DE VARIABLES DE PROCESO Y DE PRODUCTO TENIENDO EN CUENTA LOS PROCEDIMIENTOS ESTABLECIDOS","actividades": ["Realizar las mediciones de las variables."]},{"ra": "CONTROLAR LAS VARIABLES DEL PROCESO Y DEL PRODUCTO CON BASE EN TÉCNICAS ESTABLECIDAS.","actividades": ["Identificar los diferentes Ensayos y Pruebas de materiales teniendo en cuenta las características del producto."]}],"hD": 35,"hI": 9}]}
          }
        }
      }
    }
  }
}
